### ISSUE TITLE
"Cannot find module './utils'" when trying browserify

### ISSUE THREAD

**Issue by vojtech-dobes** [spoike/refluxjs#363]
I hope this is not duplicate or just my ignorance.

I have following file:

`js/components.jsx.js:`
```js
/** @jsx React.DOM */

var React = require('../bower_components/react/react-with-addons.js');
var Reflux = require('../bower_components/reflux/dist/reflux.js');
```

And I run:
```
node_modules/.bin/browserify -t reactify js/components.jsx.js -o js/main.js
```

But I am getting following error:
```
$ node_modules/.bin/browserify -t reactify ./js/components.jsx.js -o js/main.js
Error: Cannot find module './utils' from '/Users/vojtechdobes/Sites/react-demo/bower_components/reflux/dist'
    at /Users/vojtechdobes/Sites/react-demo/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/vojtechdobes/Sites/react-demo/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/vojtechdobes/Sites/react-demo/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/vojtechdobes/Sites/react-demo/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Am I doing something wrong or is it some bug in reflux? Thanks for any response in advance.

**Comment by spoike** [comment]
IIRC there is a browserify issue that can't handle some kinds of references.

Have you tried using the npm one instead?
